CONSUL_DATACENTER={{ env "CONSUL_DATACENTER" }}
DOMAIN={{ env "DOMAIN" }}
VAULT_TOKEN={{ env "VAULT_TOKEN" }}
VAULT_CACERT={{ env "VAULT_CACERT" }}
VAULT_CLIENT_CERT={{ env "VAULT_CLIENT_CERT" }}
VAULT_CLIENT_KEY={{ env "VAULT_CLIENT_KEY" }}