#!/usr/bin/env bash

# envs
ansible $1 -b -m copy -a "src=envs/build-env-vars dest=/etc/envs/"
ansible $1 -b -m copy -a "src=envs/.env-base dest=/etc/envs/"
ansible $1 -b -m copy -a "src=envs/.env-nomad-base dest=/etc/envs/"

# templates
ansible $1 -b -m copy -a "src=nomad/consul-template/configurations/server/ dest=/etc/consul-template.d/configurations/nomad"
