#!/usr/bin/env bash
echo "creating nomad user and config folders"
sudo mkdir --parents /opt/nomad
sudo mkdir --parents /etc/nomad.d
sudo useradd --system --home /etc/nomad.d --shell /bin/false nomad
sudo cp /home/pi/hashipi-config/nomad/nomad.hcl /etc/nomad.d/
chmod 700 /etc/nomad.d/
sudo chown --recursive nomad:nomad /opt/nomad /etc/nomad.d

echo "downloading nomad and moving to /usr/local/bin/"
sudo bash /home/pi/hashipi-config/nomad/scripts/get-nomad $1 $2

echo "setting up nomad autocomplete"
nomad -autocomplete-install
complete -C /usr/local/bin/nomad nomad

echo "starting nomad"
sudo cp /home/pi/hashipi-config/nomad/nomad.service /etc/systemd/system/
sudo systemctl enable nomad
sudo systemctl start nomad
sudo systemctl status nomad
