#!/bin/bash

# this allows the script to take params to override the defaults; e.g.
# bash service-init 1.6.2 amd64
# TODO :: implement flag enumeration so they don't have to be ordered
# i.e. if I want to override 2, I have to provide 1

NOMAD_VERSION=${1:-"0.10.1"}
OS_ARCHITECTURE=${2:-"arm"}

echo "Cleanup and previous configurations"
sudo rm /etc/nomad.d/*
sudo rm /etc/systemd/system/nomad.service

echo "creating nomad user and config folders"
sudo mkdir --parents /opt/nomad
sudo mkdir --parents /etc/nomad.d
sudo useradd --system --home /etc/nomad.d --shell /bin/false nomad
sudo cp /home/pi/hashipi-config/nomad/nomad.hcl /etc/nomad.d/
chmod 700 /etc/nomad.d/
sudo chown --recursive nomad:nomad /opt/nomad /etc/nomad.d

echo "downloading nomad and moving to /usr/local/bin/"
cd /home/pi
wget --output-document=nomad.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_${OS_ARCHITECTURE}.zip
unzip nomad.zip
sudo chown root:root nomad
sudo mv nomad /usr/local/bin/
rm nomad.zip

echo "setting up nomad autocomplete"
nomad -autocomplete-install
complete -C /usr/local/bin/nomad nomad

echo "starting nomad"
sudo cp /home/pi/hashipi-config/nomad/nomad.service /etc/systemd/system/
sudo systemctl enable nomad
sudo systemctl start nomad
sudo systemctl status nomad
