#!/bin/bash

# this script can accept the arguments:
# -v to specify the version to download, and
# -a to specify which architecture to download
# valid architectures are x86, amd64, arm[default], and arm64

while getopts va option
do
case "${option}"
in
v) NOMAD_VERSION=${OPTARG:-"0.10.1"};;
a) OS_ARCHITECTURE=${OPTARG:-"arm"};;
esac
done

echo "Cleanup and previous configurations"
sudo rm /etc/nomad.d/*
sudo rm /etc/systemd/system/nomad.service

echo "creating nomad user and config folders"
sudo mkdir --parents /opt/nomad
sudo mkdir --parents /etc/nomad.d
sudo useradd --system --home /etc/nomad.d --shell /bin/false nomad
sudo cp /home/pi/hashipi-config/nomad/nomad.hcl /etc/nomad.d/
chmod 700 /etc/nomad.d/
sudo chown --recursive nomad:nomad /opt/nomad /etc/nomad.d

echo "downloading nomad and moving to /usr/local/bin/"
cd /home/pi
curl -k https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_${OS_ARCHITECTURE}.zip --output nomad.zip
unzip nomad.zip
sudo chown root:root nomad
sudo mv nomad /usr/local/bin/
rm nomad.zip

echo "setting up nomad autocomplete"
nomad -autocomplete-install
complete -C /usr/local/bin/nomad nomad

echo "starting nomad"
sudo cp /home/pi/hashipi-config/nomad/nomad.service /etc/systemd/system/
sudo systemctl enable nomad
sudo systemctl start nomad
sudo systemctl status nomad
