#!/bin/bash

source /etc/envs/build-env-vars

#!/bin/bash

source /etc/envs/build-env-vars

sudo DOMAIN=$DOMAIN \
    CONSUL_DATACENTER=$CONSUL_DATACENTER \
    VAULT_TOKEN=$VAULT_TOKEN \
    consul-template \
        -config /etc/consul-template.d/certificates/vault/build-vault-server-certs.hcl -vault-addr $1 \
        -once


sudo ln -s /etc/certs/vault-ca.crt /usr/local/share/ca-certificates/
sudo update-ca-certificates

sudo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_REGION=$AWS_REGION \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    VAULT_AGENT_ADDR=$VAULT_AGENT_ADDR \
    VAULT_API_ADDR=$VAULT_API_ADDR \
    VAULT_AWSKMS_SEAL_KEY_ID=$VAULT_AWSKMS_SEAL_KEY_ID \
    VAULT_CACERT=$VAULT_CACERT \
    VAULT_SERVER_AGENT_CERT=$VAULT_SERVER_AGENT_CERT \
    VAULT_SERVER_AGENT_KEY=$VAULT_SERVER_AGENT_KEY \
    VAULT_CLUSTER_ADDR=$VAULT_CLUSTER_ADDR \
    VAULT_DISABLE_MLOCK=$VAULT_DISABLE_MLOCK \
    VAULT_LOG_FORMAT=$VAULT_LOG_FORMAT \
    VAULT_LOG_LEVEL=$VAULT_LOG_LEVEL \
    VAULT_RAFT_NODE_ID=$VAULT_RAFT_NODE_ID \
    VAULT_RAFT_PATH=$VAULT_RAFT_PATH \
    VAULT_UI=$VAULT_UI \
        consul-template \
            -config /etc/consul-template.d/configurations/vault/build-server-config-tls.hcl \
            -once
