#!/usr/bin/env bash

# create EnvironmentFile for service based on deployed env vars
ansible $1 -b -a "sudo bash /etc/consul-template.d/certificates/vault/build-vault-client-cert-gen-templates.sh"

# install certificate generation service
ansible $1 -b -a "sudo bash /etc/consul-template.d/certificates/vault/update-client-cert-gen-systemd-service.sh"
