#!/bin/bash

# this allows the script to take params to override the defaults; e.g.
# bash service-init 1.6.2 amd64
# TODO :: implement flag enumeration so they don't have to be ordered
# i.e. if I want to override 2, I have to provide 1

VAULT_VERSION=${1:-"1.3.1"}
OS_ARCHITECTURE=${2:-"arm"}

echo "Cleanup and previous configurations"
sudo rm /etc/vault.d/*
sudo rm /etc/systemd/system/vault.service

echo "creating vault user and config folders"
sudo mkdir --parents /opt/vault
sudo mkdir --parents /etc/vault.d
sudo useradd --system --home /etc/vault.d --shell /bin/false vault
sudo cp /home/pi/hashipi-config/vault/vault.hcl /etc/vault.d/
sudo chown --recursive vault:vault /opt/vault /etc/vault.d
sudo chmod 700 /etc/vault.d/

echo "downloading vault and moving to /usr/local/bin/"
cd /home/pi
wget --output-document=vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${OS_ARCHITECTURE}.zip
unzip vault.zip
sudo mv vault /usr/local/bin/vault
rm vault.zip

echo "give Vault the ability to use the mlock syscall without running the process as root. The mlock syscall prevents memory from being swapped to disk"
sudo setcap cap_ipc_lock=+ep /usr/local/bin/vault

echo "downloading vault and moving to /usr/local/bin/"
sudo bash /home/pi/hashipi-config/vault/scripts/get-vault $1 $2

echo "setting up vault autocomplete"
vault -autocomplete-install
complete -C /usr/local/bin/vault vault

echo "installing vault"
sudo cp /home/pi/hashipi-config/vault/vault.service /etc/systemd/system/

sudo chown -R vault:vault /opt/vault /etc/vault.d

sudo systemctl enable vault
sudo systemctl start vault
sudo systemctl status vault