#!/bin/bash

# this script can accept the arguments:
# -v to specify the version to download, and
# -a to specify which architecture to download
# valid architectures are x86, amd64, arm[default], and arm64

# this allows the script to take params to override the defaults; e.g.
# bash service-init 0.24.1 amd64
# TODO :: implement flag enumeration so they don't have to be ordered
# i.e. if I want to override 2, I have to provide 1

CONSUL_VERSION=${1:-"0.24.1"}
OS_ARCHITECTURE=${2:-"arm"}

echo "Cleanup and previous configurations"
sudo rm /etc/consul-template.d/*
sudo rm /etc/systemd/system/consul-template.service

echo "creating consul-template user and config folders"
sudo mkdir --parents /etc/consul-template.d
sudo mkdir --parents /opt/consul-template
sudo useradd --system --home /etc/consul-template.d --shell /bin/false consul-template
sudo chown --recursive consul-template:consul-template /opt/consul-template /etc/consul-template.d
sudo cp /home/pi/hashipi-config/consul-template/consul-template.hcl /etc/consul-template.d/
sudo chmod 640 /etc/consul-template.d/consul-template.hcl

echo "downloading consul-template and moving to /usr/local/bin/"
cd /home/pi
sudo bash hashipi-config/consul-template/get-consul-template $1 $2

echo "setting up consul-template autocomplete"
consul-template -autocomplete-install
complete -C /usr/local/bin/consul-template consul-template

echo "starting consul-template"
sudo cp /home/pi/hashipi-config/consul-template/consul-template.service /etc/systemd/system/
sudo systemctl enable consul-template
sudo systemctl start consul-template
sudo systemctl status consul-template