#!/bin/bash

source /etc/envs/build-env-vars

sudo CONSUL_ACL_ENABLED=$CONSUL_ACL_ENABLED \
CONSUL_ACL_DEFAULT_POLICY=$CONSUL_ACL_DEFAULT_POLICY \
CONSUL_ACL_DOWN_POLICY=$CONSUL_ACL_DOWN_POLICY \
CONSUL_ACL_ENABLE_TOKEN_PERSISTENCE=$CONSUL_ACL_ENABLE_TOKEN_PERSISTENCE \
CONSUL_HTTP_TOKEN=$CONSUL_HTTP_TOKEN \
    consul-template \
        -config /etc/consul-template.d/configurations/consul/build-acl-config.hcl \
        -once
