#!/bin/bash

source /etc/envs/build-env-vars

sudo DOMAIN=$DOMAIN \
    CONSUL_DATACENTER=$CONSUL_DATACENTER \
    consul-template \
        -config /etc/consul-template.d/certificates/consul/build-consul-client-certs.hcl -vault-addr $1 \
        -once