#!/bin/bash

source /etc/envs/build-env-vars

sudo DOMAIN=$DOMAIN \
    CONSUL_DATACENTER=$CONSUL_DATACENTER \
    VAULT_TOKEN=$VAULT_TOKEN \
    consul-template \
        -config /etc/consul-template.d/certificates/consul/consul-client-certs.hcl -vault-addr $1 \
        -once

sudo ln -s /etc/certs/consul-ca.crt /usr/local/share/ca-certificates/
sudo update-ca-certificates

sudo CONSUL_CACERT=$CONSUL_CACERT \
    CONSUL_CLIENT_CERT=$CONSUL_CLIENT_CERT \
    CONSUL_CLIENT_KEY=$CONSUL_CLIENT_KEY \
    CONSUL_HTTP_SSL_VERIFY=$CONSUL_HTTP_SSL_VERIFY \
        consul-template \
            -config /etc/consul-template.d/configurations/consul/build-client-tls.hcl \
            -once
