#!/bin/bash

ansible $1 -b -m copy -a "src=envs/.env-consul-gossip dest=/etc/envs/"
ansible $1 -b -m copy -a "src=consul/consul-template/configurations/gossip/ dest=/etc/consul-template.d/configurations/consul/templates"
