#!/bin/bash

# envs
ansible $1 -b -m copy -a "src=envs/.env-base dest=/etc/envs/"
ansible $1 -b -m copy -a "src=envs/.env-consul-acl dest=/etc/envs/"
ansible $1 -b -m copy -a "src=envs/.env-consul-base dest=/etc/envs/"

# templates
ansible $1 -b -m copy -a "src=consul/consul-template/configurations/base/ dest=/etc/consul-template.d/configurations/consul"
ansible $1 -b -m copy -a "src=consul/consul-template/configurations/server/ dest=/etc/consul-template.d/configurations/consul"
