#!/bin/bash

ansible $1 -b -m copy -a "src=consul-template/certificates/consul/cli/ dest=/etc/consul-template.d/certificates/consul"
ansible $1 -b -m copy -a "src=consul-template/certificates/consul/client/ dest=/etc/consul-template.d/certificates/consul"
