#!/usr/bin/env bash
echo "creating consul user and config folders"
sudo mkdir --parents /etc/consul.d
sudo mkdir --parents /opt/consul
sudo useradd --system --home /etc/consul.d --shell /bin/false consul
sudo chown --recursive consul:consul /opt/consul /etc/consul.d
sudo cp /home/pi/hashipi-config/consul/consul.hcl /etc/consul.d/
sudo chmod 640 /etc/consul.d/consul.hcl

echo "downloading consul and moving to /usr/local/bin/"
sudo bash /home/pi/hashipi-config/consul/scripts/get-consul $1 $2

echo "setting up consul autocomplete"
consul -autocomplete-install
complete -C /usr/local/bin/consul consul

echo "starting consul"
sudo cp /home/pi/hashipi-config/consul/consul.service /etc/systemd/system/
sudo systemctl enable consul
sudo systemctl start consul
sudo systemctl status consul