#!/bin/bash

CONSUL_VERSION="1.6.1"
OS_ARCHITECTURE=arm

echo "Cleanup and previous configurations"
sudo rm /etc/consul.d/*
sudo rm /etc/systemd/system/consul.service

echo "creating consul user and config folders"
sudo mkdir --parents /etc/consul.d
sudo mkdir --parents /opt/consul
sudo useradd --system --home /etc/consul.d --shell /bin/false consul
sudo chown --recursive consul:consul /opt/consul /etc/consul.d
sudo cp /home/pi/hashipi-config/consul/consul.hcl /etc/consul.d/
sudo chmod 640 /etc/consul.d/consul.hcl

echo "downloading consul and moving to /usr/local/bin/"
cd /home/pi
curl -k https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_${OS_ARCHITECTURE}.zip --output consul.zip
unzip consul.zip
sudo chown root:root consul
sudo mv consul /usr/local/bin/
rm consul.zip

echo "setting up consul autocomplete"
consul -autocomplete-install
complete -C /usr/local/bin/consul consul

echo "starting consul"
sudo cp /home/pi/hashipi-config/consul/consul.service /etc/systemd/system/
sudo systemctl enable consul
sudo systemctl start consul
sudo systemctl status consul