#!/bin/bash

# this script can accept the arguments:
# -v to specify the version to download, and
# -a to specify which architecture to download
# valid architectures are x86, amd64, arm[default], and arm64

# this allows the script to take params to override the defaults; e.g.
# bash service-init 1.6.2 amd64
# TODO :: implement flag enumeration so they don't have to be ordered
# i.e. if I want to override 2, I have to provide 1

CONSUL_VERSION=${1}
OS_ARCHITECTURE=${2}

echo "Cleanup and previous configurations"
sudo rm /etc/consul.d/*
sudo rm /etc/systemd/system/consul.service

echo "creating consul user and config folders"
sudo mkdir --parents /etc/consul.d
sudo mkdir --parents /opt/consul
sudo useradd --system --home /etc/consul.d --shell /bin/false consul
sudo chown --recursive consul:consul /opt/consul /etc/consul.d
sudo cp /home/pi/hashipi-config/consul/consul.hcl /etc/consul.d/
sudo chmod 640 /etc/consul.d/consul.hcl

echo "downloading consul and moving to /usr/local/bin/"
cd /home/pi
sudo bash hashipi-config/consul/get-consul $1 $2

echo "setting up consul autocomplete"
consul -autocomplete-install
complete -C /usr/local/bin/consul consul

echo "starting consul"
sudo cp /home/pi/hashipi-config/consul/consul.service /etc/systemd/system/
sudo systemctl enable consul
sudo systemctl start consul
sudo systemctl status consul