#!/bin/bash

# this allows the script to take params to override the defaults; e.g.
# bash service-init 1.6.2 amd64
# TODO :: implement flag enumeration so they don't have to be ordered
# i.e. if I want to override 2, I have to provide 1

VAULT_VERSION=${1:-"1.3.0"}
OS_ARCHITECTURE=${2:-"arm"}

echo "Cleanup and previous configurations"
sudo rm /etc/vault.d/*
sudo rm /etc/systemd/system/vault.service

echo "creating vault user and config folders"
sudo mkdir --parents /opt/vault
sudo mkdir --parents /etc/vault.d
sudo useradd --system --home /etc/vault.d --shell /bin/false vault
sudo cp /home/pi/hashipi-config/vault/vault.hcl /etc/vault.d/
sudo chown --recursive vault:vault /opt/vault /etc/vault.d
sudo chmod 700 /etc/vault.d/

echo "downloading vault and moving to /usr/local/bin/"
cd /home/pi
wget --output-document=vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${OS_ARCHITECTURE}.zip
unzip vault.zip
sudo mv vault /usr/local/bin/vault
rm vault.zip

echo "give Vault the ability to use the mlock syscall without running the process as root. The mlock syscall prevents memory from being swapped to disk"
sudo setcap cap_ipc_lock=+ep /usr/local/bin/vault

echo "setting up vault autocomplete"
vault -autocomplete-install
complete -C /usr/local/bin/vault vault

echo "installing vault"
sudo cat << EOF > /etc/systemd/system/vault.service
[Unit]
Description="HashiCorp Vault - A tool for managing secrets"
Documentation=https://www.vaultproject.io/docs/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/vault.d/vault.hcl
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=vault
Group=vault
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
PrivateDevices=yes
SecureBits=keep-caps
AmbientCapabilities=CAP_IPC_LOCK
Capabilities=CAP_IPC_LOCK+ep
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
NoNewPrivileges=yes
ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=5
TimeoutStopSec=30
StartLimitInterval=60
StartLimitIntervalSec=60
StartLimitBurst=3
LimitNOFILE=65536
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
EOF

sudo chown -R vault:vault /opt/vault /etc/vault.d

sudo systemctl enable nomad
sudo systemctl start nomad
sudo systemctl status nomad