#!/usr/bin/env bash

source /etc/envs/build-env-vars
  
sudo CONSUL_CACERT=$CONSUL_CACERT \
  CONSUL_CLIENT_CERT=$CONSUL_CLIENT_CERT \
  CONSUL_CLIENT_KEY=$CONSUL_CLIENT_KEY \
  CONSUL_DATACENTER=$CONSUL_DATACENTER \
  CONSUL_HTTP_ADDR=$CONSUL_HTTP_ADDR \
  CONSUL_HTTP_TOKEN=$CONSUL_HTTP_TOKEN \
  CONSUL_NODE_NAME=$CONSUL_NODE_NAME \
  HOSTNAME=$HOSTNAME \
  NOMAD_CACERT=$NOMAD_CACERT \
  NOMAD_CLIENT_CERT=$NOMAD_CLIENT_CERT \
  NOMAD_CLIENT_KEY=$NOMAD_CLIENT_KEY \
  VAULT_ADDR=$VAULT_ADDR \
  VAULT_CACERT=$VAULT_CACERT \
  VAULT_CLIENT_CERT=$VAULT_CLIENT_CERT \
  VAULT_CLIENT_KEY=$VAULT_CLIENT_KEY \
  VAULT_TOKEN=$VAULT_TOKEN \
    consul-template -config=/etc/consul-template.d/configurations/grafana-agent/grafana-agent.hcl